[package]
name = "bushel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
objc2 = "0.5.2"
objc2-foundation = { version = "0.2.2", features = ["NSObject", "NSString"] }
